### ISSUE TITLE
【BUG】新版文章页面的评论区，评论无法打空格

### ISSUE THREAD

**Issue by GuGuGee** [halo-dev/plugin-comment-widget#108]
在文章管理后台回复访客评论，功能一切正常。
在文章页面回复访客评论，会出现无法打空格的情况。

以下是博客配置信息：

- 外部访问地址: https://blog.laoda.de
- 启动时间: 2024-03-25 10:32
- 版本: 2.13.1
- 构建时间: 2024-03-06 17:40
- Git Commit: 9473261
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.1.0
- 操作系统: Linux / 6.1.0-18-amd64
- 已激活主题: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [Meilisearch](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [朋友圈](https://github.com/chengzhongxue/plugin-friends)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

**Comment by ruibaby** [comment]
经过对 [blog.laoda.de](https://blog.laoda.de/) 的调试，发现是主题的 js 影响的。

把这个事件移除掉就正常了：

<img width="439" alt="image" src="https://github.com/halo-dev/plugin-comment-widget/assets/21301288/0f48cc7d-2d6c-4cde-9b3c-29b4bf3c11a9">

<img width="1283" alt="image" src="https://github.com/halo-dev/plugin-comment-widget/assets/21301288/bbf5ea6d-9413-49ac-9bc3-86b08fb107ba">

**Comment by GuGuGee** [comment]
> 经过对 [blog.laoda.de](https://blog.laoda.de/) 的调试，发现是主题的 js 影响的。
> 
> 把这个事件移除掉就正常了：
> 
> <img alt="image" width="439" src="https://private-user-images.githubusercontent.com/21301288/316409815-0f48cc7d-2d6c-4cde-9b3c-29b4bf3c11a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNDkzOTQsIm5iZiI6MTcxMTM0OTA5NCwicGF0aCI6Ii8yMTMwMTI4OC8zMTY0MDk4MTUtMGY0OGNjN2QtMmQ2Yy00Y2RlLTliM2MtMjliNGJmM2MxMWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA2NDQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZjJjZmY3Y2RhMTVmOWNlMDM0ZDQxNDAzN2E1ZmVlY2RlZDNjYjcxZmU4YmY3N2EyM2E5N2FlM2UyMTJjOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vQaYCOPNb54tpb8tqoQyaLauyXxLYM0U9b4h5aGG6RY"> <img alt="image" width="1283" src="https://private-user-images.githubusercontent.com/21301288/316409839-bbf5ea6d-9413-49ac-9bc3-86b08fb107ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNDkzOTQsIm5iZiI6MTcxMTM0OTA5NCwicGF0aCI6Ii8yMTMwMTI4OC8zMTY0MDk4MzktYmJmNWVhNmQtOTQxMy00OWFjLTliYzMtODZiMDhmYjEwN2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA2NDQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNjkzNzJkZmFkNTMyYzAwODdkZjhjNGRkZGM4MjE3M2JmNTI5MmYyYTBlMzUyZWE0NzY0ZWMzNGNlN2IyZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I4S_VZcz9KQILUXVPuXU7-dhkGAhuwsRFgCmtigHLNk">

谢谢！我反馈一下主题作者
