### ISSUE TITLE
2.0版本后评论首次无法显示，需要刷新才可以

### ISSUE THREAD

**Issue by 666ghj** [halo-dev/plugin-comment-widget#112]
![image](https://github.com/halo-dev/plugin-comment-widget/assets/110395318/301b5b4d-a744-4567-b44d-2d6571617336)
![image](https://github.com/halo-dev/plugin-comment-widget/assets/110395318/74a3a8da-13b6-4654-98a1-e24f7fa87e79)

**Comment by 666ghj** [comment]
站点地址：http://lovexl.top

**Comment by LIlGG** [comment]
应该是主题端使用了 PJAX 后，自行处理评论组件导致。并且在评论组件 2.x 之后，将会默认向 `Header` 中插入 js，因此主题端也无需再自行处理评论组件。 建议向主题仓库提交 issue
