### ISSUE TITLE
希望评论能支持图片

### ISSUE THREAD

**Issue by qiushaocloud** [halo-dev/plugin-comment-widget#125]
希望评论能支持图片，如果能支持视频就更好了，数据存储希望能和后台一样，配置存储到本地还是其它云存储(如：S3)

**Comment by qiushaocloud** [comment]
或者能存储到 github 也行，就是把 github 当图床

**Comment by ruibaby** [comment]
/triage duplicate

See https://github.com/halo-dev/plugin-comment-widget/issues/102 https://github.com/halo-dev/plugin-comment-widget/issues/66

/close
