### ISSUE TITLE
升级最新版本后线上CDN下无法加载。

### ISSUE THREAD

**Issue by cpyczd** [halo-dev/plugin-comment-widget#128]
原来的版本一直好好的在用，升级最新的之后直接不能用了，一直在加载。
GET https://www.xxxxxx.com/archives/[object%20Object] net::ERR_ABORTED 400 (Bad Request)
comment-widget.iife.js?version=2.1.0:63。 但是在dev环境下可以正常加载。
我重新卸载新版本安装：1.9版本的刷新CDN后重新测试又恢复了。 Halo是最新的版本主题也是最新的版本。
请问这个问题是怎么回事？谢谢。

**Comment by JohnNiang** [comment]
建议提供一下 Halo 的版本。如果不是最新的，建议都升级至最新后重试。

/triage needs-information

**Comment by cpyczd** [comment]
Halo：  2.15.2版本
(2024-05-24下测试)主题也是最新的，我尝试了不同的主题。 然后放到线上后还是一样结果。

**Comment by ruibaby** [comment]
未复现，也没有收到类似反馈。建议提供你线上可复现的链接，目前我们没有任何问题判断依据。

**Comment by cpyczd** [comment]
我把插件升级到2.2了现在错误复现了同一个环境下：
走CDN的域名：https://www.saisaiwa.com/archives/tspi-build-ubuntu
不走CDN的域名：http://dev.saisaiwa.com/archives/tspi-build-ubuntu

**Comment by ruibaby** [comment]
建议检查你的 CDN 缓存配置，这很明显是页面被缓存，走 CDN 的域名访问的 HTML 结构都不同。

<img width="875" alt="image" src="https://github.com/halo-dev/plugin-comment-widget/assets/21301288/288d5997-7b94-4b43-8e1e-4aa393e9dd41">
<img width="697" alt="image" src="https://github.com/halo-dev/plugin-comment-widget/assets/21301288/cfd97bcf-a2d5-4d52-87ee-dbd37771161e">

**Comment by JohnNiang** [comment]
建议检查一下 CDN 缓存，是否忽略了参数进行缓存了。

<img width="737" alt="image" src="https://github.com/halo-dev/plugin-comment-widget/assets/16865714/26a6b52c-2a55-4dd1-b605-3443161dcd63">

**Comment by cpyczd** [comment]
![image](https://github.com/halo-dev/plugin-comment-widget/assets/31030154/ca5e8997-2768-4e84-bee2-23151f378964)
![image](https://github.com/halo-dev/plugin-comment-widget/assets/31030154/5c7600c4-b19a-4a34-a218-48d490812d51)
![image](https://github.com/halo-dev/plugin-comment-widget/assets/31030154/26818b97-ec2c-430a-b5ce-24279b4bd2c7)
![image](https://github.com/halo-dev/plugin-comment-widget/assets/31030154/a02b86d9-670e-4e5e-ae79-0f3201bde985)

强制刷新了缓存，问题貌似还是有呢？

**Comment by cpyczd** [comment]
确认为ngix二次缓存问题，问题已解决！ 感谢作者的耐心回答
