### ISSUE TITLE
邮箱输入框提示文字修改建议

### ISSUE THREAD

**Issue by HowieHz** [halo-dev/plugin-comment-widget#129]
![image](https://github.com/halo-dev/plugin-comment-widget/assets/94725606/12dedd52-0689-42e9-bd0b-4767b90b7816)
修改建议：`电子邮件` -> `电子邮件（用于接收回复提醒）`
或者在设置提供可配置项

提这个 issue 的原因是这个月有不下三个人问我这个电子邮件填了啥用了

**Comment by Cat66666666** [comment]
邮箱一个方面是获取头像用的

**Comment by HowieHz** [comment]
https://github.com/halo-dev/plugin-comment-widget/pull/147
