### ISSUE TITLE
请求支持MarkDown语法

### ISSUE THREAD

**Issue by 0zjn0123** [halo-dev/plugin-comment-widget#141]
请求支持MarkDown语法，这样可以让评论更好看更美观

**Comment by GuGuGee** [comment]
附议

![image](https://github.com/user-attachments/assets/9ec39494-e21a-4598-ae4a-23788020f76f)

如果代码可以以代码块的形式显示，会更易阅读一些～

**Comment by lhDream** [comment]
同样需要, 不知道有没有计划添加 😕
