### ISSUE TITLE
是我打开方式不对还是什么？建议看看

### ISSUE THREAD

**Issue by Cat66666666** [halo-dev/plugin-comment-widget#146]
当我开开匿名评论，且需要输入验证码评论，提示登陆
![1723046772331](https://github.com/user-attachments/assets/8c83c8fa-5375-48fd-8b7e-6a7c8a20117a)
当我登陆后却没有匿名访问
![1723046873825](https://github.com/user-attachments/assets/c6e0a631-44c4-4af1-a328-3aa351b3363b)
设置如下，大脑疯狂运转0.0
![1723046950346](https://github.com/user-attachments/assets/953bbc9a-ef25-4a2b-85f5-7d4e0afdb72c)
这逻辑是不是不对啊！！！！！！！

**Comment by HowieHz** [comment]
![image](https://github.com/user-attachments/assets/1246fbdf-6373-4b2d-a297-a048c75d67ac)
第三项关掉

**Comment by ruibaby** [comment]
需要在不允许匿名评论时，不显示验证码，已经在 https://github.com/halo-dev/plugin-comment-widget/pull/148 中修复。

**Comment by Cat66666666** [comment]
> ![image](https://private-user-images.githubusercontent.com/94725606/356086997-1246fbdf-6373-4b2d-a297-a048c75d67ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTY1OTMsIm5iZiI6MTcyMzExNjI5MywicGF0aCI6Ii85NDcyNTYwNi8zNTYwODY5OTctMTI0NmZiZGYtNjM3My00YjJkLWEyOTctYTA0OGM3NWQ2N2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDExMjQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwNjY0ZDQ0N2Y2M2QzODBmZTU2YjI0MGY3Nzc5NGVmZDhjMTAyNDE5ZTRkMGUwNTlhNGI4NGNjOGZmMDY4MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sbSEGE2dQwoF5rYFS5AZsoqzenysB0TClc5YwPIlMM8) 第三项“仅允许注册用户评论”关掉第三项“仅允许注册用户评论”关掉

解决了，原来是设置问题
