### ISSUE TITLE
部分主题页脚会盖住表情选择框

### ISSUE THREAD

**Issue by ixianhao** [halo-dev/plugin-comment-widget#155]
部分主题页脚会盖住表情选择框，是不是可以把form__emoji-panel样式改为position: relative;

**Comment by ruibaby** [comment]
这个问题建议由主题适配，如果改为 relative position，将不会有悬浮效果。

![Image](https://github.com/user-attachments/assets/6758d08f-fc05-4c55-b23f-0b927a550492)

相关问题：https://github.com/halo-dev/plugin-comment-widget/issues/76
