### ISSUE TITLE
halo中个人中心-消息下收到的评论通知，点击的跳转链接是localhost:8090,halo使用的docker-compose部署，端口设置的80，域名访问。问下在哪里修改评论的跳转ip或者域名

### ISSUE THREAD

**Issue by 20191864231** [halo-dev/plugin-comment-widget#159]
![Image](https://github.com/user-attachments/assets/e9ea97dc-be87-4e5e-9a81-6685c87f4b34)

![Image](https://github.com/user-attachments/assets/8b4c202f-96e8-47ee-a5c4-077fa36785b4)
![Image](https://github.com/user-attachments/assets/7d672628-ca6a-4e6b-8f46-4d02a46025f6)

**Comment by ruibaby** [comment]
你的 halo.external-url 应该设置为你访问的域名，而不是 localhost。

**Comment by 20191864231** [comment]
> 你的 halo.external-url 应该设置为你访问的域名，而不是 localhost。
谢谢回答，我的马赛克可能遮的太大了，使用的是域名没错的。

**Comment by 20191864231** [comment]
> 你的 halo.external-url 应该设置为你访问的域名，而不是 localhost。
/
解决了，原因是那是备份的历史记录，而在历史的版本中我确实使用的localhost作为halo.external-url，新的评论是没有问题的，感谢
