### ISSUE TITLE
评论展示

### ISSUE THREAD

**Issue by wxyShine** [halo-dev/plugin-comment-widget#55]
halo2.9  评论插件1.7.0  友连1.3.1
![image](https://github.com/halo-sigs/plugin-comment-widget/assets/42802152/f7333cbd-76ef-4a18-98b4-7e69724c0abe)

友连 页面 评论展示未知

**Comment by ruibaby** [comment]
链接页面本身应该不支持评论，是如何让链接页面支持评论的呢？

/triage needs-information
