### ISSUE TITLE
评论区在白天/黑夜模式切换后的样式问题

### ISSUE THREAD

**Issue by Einstein-schrodinger** [halo-dev/plugin-comment-widget#56]
评论区在白天/黑夜模式手动切换后，样式不能跟随适配，需要手动刷新之后才能适配，这是插件的问题还是主题的问题？
如图所示，黑夜->白天之后，一些样式依旧是暗色，并且红框内的用户名因为是白色而无法查看。
![image](https://github.com/halo-sigs/plugin-comment-widget/assets/62790820/11f09b4e-f100-4fbc-b1c5-78ffa80b3d55)

**Comment by AirboZH** [comment]
我觉得这个地方目前应该主题适配，
chirpy和hao两个主题目前都是这样做的 参考https://github.com/AirboZH/halo-theme-chirpy/blob/master/src/js/modules/halo.js

因为主题切换模式的方法比较多样，插件没有办法去监听主题的模式切换（除非定一个规范）
需要主题手动调用/修改插件配置

**Comment by ruibaby** [comment]
> 因为主题切换模式的方法比较多样，插件没有办法去监听主题的模式切换（除非定一个规范）

👍我们确实在考虑为主题的颜色模式提供一套 JS API（规范），让所有主题相关的地方都主动实现，包括插件在主题端提供的界面，比如搜索和评论。

**Comment by ruibaby** [comment]
晚点我会在 Halo 提交一个 issue。

**Comment by AirboZH** [comment]
太好了，搜索插件的白天/黑夜模式切换也提上日程吧🫡

**Comment by ruibaby** [comment]
我将按照 https://github.com/halo-dev/plugin-search-widget/pull/20 实现让主题自定义样式。
