### ISSUE TITLE
PC端回复使用emoj表情包，无法选中

### ISSUE THREAD

**Issue by yovvis** [halo-dev/plugin-comment-widget#76]
环境：PC端
现象：回复评论之后，再点击回复选择emoj就会出现问题：图层展示无法选中
截图：![微信图片_20240130113354](https://github.com/halo-dev/plugin-comment-widget/assets/60733474/d09fcdff-b18d-4265-ab31-633c9c442057)

**Comment by yovvis** [comment]
> 感谢反馈此问题，使用的是哪个主题呢？我复现一下。

目前使用的是pix主题，halo版本是2.12.3

**Comment by yovvis** [comment]
> 感谢反馈此问题，使用的是哪个主题呢？我复现一下。

![image](https://github.com/halo-dev/plugin-comment-widget/assets/60733474/128e2764-be94-4238-b0b9-9f2668c84814)
新版本也是一样哈，作者大大

**Comment by ruibaby** [comment]
看了一下这个主题，可能需要向这个主题反馈进行兼容，因为发现这个主题的 footer 部分设置了 z-index：

<img width="1527" alt="image" src="https://github.com/halo-dev/plugin-comment-widget/assets/21301288/580f835d-84a6-4de4-8be2-974943b436d0">

主题只需要主动去给评论的最外层 dom 节点设置需要的 z-index 即可。

<img width="1571" alt="image" src="https://github.com/halo-dev/plugin-comment-widget/assets/21301288/764f223a-98af-4a69-ae16-557469dec4cb">

**Comment by yovvis** [comment]
> 看了一下这个主题，可能需要向这个主题反馈进行兼容，因为发现这个主题的 footer 部分设置了 z-index：
> 
> <img alt="image" width="1527" src="https://private-user-images.githubusercontent.com/21301288/310066910-580f835d-84a6-4de4-8be2-974943b436d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mzc3ODQsIm5iZiI6MTcwOTYzNzQ4NCwicGF0aCI6Ii8yMTMwMTI4OC8zMTAwNjY5MTAtNTgwZjgzNWQtODRhNi00ZGU0LThiZTItOTc0OTQzYjQzNmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDExMTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlZGVmMTZlM2QwODg4NDQyNWU0NThiNjEwOTg0YzJjYzYzMDlmNDRhNWVhYzU4ZjZmMTNhYjFkYTNhMzc1ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5c32ZvWapDObTXykmbcM6-SUohBep1u_bNOWK1dXWVw">
> 主题只需要主动去给评论的最外层 dom 节点设置需要的 z-index 即可。
> 
> <img alt="image" width="1579" src="https://private-user-images.githubusercontent.com/21301288/310067344-246dcb37-f17f-4970-9b17-ef111d983811.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mzc3ODQsIm5iZiI6MTcwOTYzNzQ4NCwicGF0aCI6Ii8yMTMwMTI4OC8zMTAwNjczNDQtMjQ2ZGNiMzctZjE3Zi00OTcwLTliMTctZWYxMTFkOTgzODExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDExMTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyOTdmNzNjYmM4ZDEyYTkxNTJhNDQyNjM1ZWJiZDc5M2UzMjc1YzU5ZDQxNWUzMTc1MmVkZjhjYWE0MTU2NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fH9uXZsXtdxSfLxjuktA-Wzd1tP1DXX-R8_0pvpcX_E">

好滴，我去联系开发，非常感谢

**Comment by ruibaby** [comment]
> 文章中出现的评论问题已联系主题作者，瞬间版本1.5.1，以及上一个版本也是出现相同问题

可能都需要主题根据主题的情况适配。
