### ISSUE TITLE
Gravatar 能自定义镜像服务器吗?

### ISSUE THREAD

**Issue by jkjoy** [halo-dev/plugin-comment-widget#77]
已知Gravatar无法显示

**Comment by ruibaby** [comment]
当前 Halo2 仅支持系统头像，还不支持类似于 Gravatar 的三方头像系统，所以暂时可能不是很好修改 Gravatar 的源，后续可以看看是否可以为评论提供头像来源的扩展点，届时就可以兼容 Gravatar 头像源了。

**Comment by jkjoy** [comment]
只要能自定义就好了 替换 官网Gravatar.com 应该就可以了吧
