### ISSUE TITLE
评论区域大小问题

### ISSUE THREAD

**Issue by jiewenhuang** [halo-dev/plugin-comment-widget#78]
在写主题的时候为了计算rem方便，有时候会将font-size设置为62.5% 这样则会导致评论区和搜索框偏小的问题呢，评论模块我可以手动暴露一个font-size 出来整体调整，但是对评论似乎是无效的，这个有什么好的处理方法吗？

**Comment by ruibaby** [comment]
期望能够像搜索组件的 https://github.com/halo-dev/plugin-search-widget/pull/20 改动一样，使用 css 变量来控制样式，包括配色。

此外，期望能够和 https://github.com/halo-dev/plugin-search-widget/pull/18 一样使用 Lit 重构组建之后再来进行这个改动，我也已经在进行中。
