### ISSUE TITLE
Halo2.12.4环境Earth主题1.7.1下评论链接错误问题

### ISSUE THREAD

**Issue by YusCoding** [halo-dev/plugin-comment-widget#81]
Halo2.12.4环境Earth主题1.7.1下评论者网站url跳转错误，点击评论者头像链接跳转的目标网址是当前站点地址+archive +评论者站点地址的格式，如图所示
![image](https://github.com/halo-dev/plugin-comment-widget/assets/33707489/a295917e-76ae-4805-960a-e16e0a25c8e7)

**Comment by ruibaby** [comment]
应该是网址没有带 https://，将在 https://github.com/halo-dev/plugin-comment-widget/pull/80 中修复。
