### ISSUE TITLE
BUG: 2.0.0打开表情面板时高度出现样式问题

### ISSUE THREAD

**Issue by mjsoftking** [halo-dev/plugin-comment-widget#91]
### 默认主题
![image](https://github.com/halo-dev/plugin-comment-widget/assets/23021469/db0171a8-6720-4d14-9184-f998ededc79e)

### dream主题
![image](https://github.com/halo-dev/plugin-comment-widget/assets/23021469/78671572-61ed-4266-8ae2-f7a2bf52f808)
- 高度过长，部分位置被footer部分遮挡

**Comment by ruibaby** [comment]
可以参考：https://github.com/halo-dev/plugin-comment-widget/issues/76

**Comment by mjsoftking** [comment]
需要把页脚设置为 -1 才行
