### ISSUE TITLE
希望点击评论图标后编辑器能展示在可视区域

### ISSUE THREAD

**Issue by guqing** [halo-dev/plugin-comment-widget#94]
目前如果点击屏幕下方的评论图标后, 虽然展开了编辑框, 但是需要滚动才能看到, 建议显示编辑框时自动滚动到可视区域

/kind improvement

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/plugin-comment-widget/pull/104 中实现。

/close
