### ISSUE TITLE
评论组件是否可以增加 Gravatar 源设置

### ISSUE THREAD

**Issue by guqing** [halo-dev/plugin-comment-widget#97]
评论组件是否可以支持 Gravatar 源设置以便匿名用户评论时可以根据邮箱地址显示头像,或者增加没有头像时的默认头像选项设置如根据名称生成等策略

/kind feature

**Comment by jkjoy** [comment]
同感.
国内用户用着全是红叉

**Comment by mashirot** [comment]
IMO，现在插件是从 `this.comment?.owner.avatar` 拿的avatar路径，后端是否只需在返回的comment对象里加上owner邮箱的hash，然后评论插件根据邮箱hash拼出请求，再从gravatar拿图，见[Image Requests](https://docs.gravatar.com/general/images/)

**Comment by JohnNiang** [comment]
Hi @mashirot ，感觉 avatar 又后端拼接可能会更好，不过仍然可以考虑把邮箱的 hash 放到 annotations 中返回。

**Comment by mashirot** [comment]
> Hi @mashirot ，感觉 avatar 又后端拼接可能会更好，不过仍然可以考虑把邮箱的 hash 放到 annotations 中返回。

好的，如果我想做这个issue该怎么操作，因为涉及到两个仓库，先到halo仓库提pr将comment的修改引入，再对此仓库发pr吗

**Comment by guqing** [comment]
> > Hi @mashirot ，感觉 avatar 又后端拼接可能会更好，不过仍然可以考虑把邮箱的 hash 放到 annotations 中返回。
> 
> 好的，如果我想做这个issue该怎么操作，因为涉及到两个仓库，先到halo仓库提pr将comment的修改引入，再对此仓库发pr吗

这个功能本身就是想在插件中实现的，不希望去改 halo

**Comment by mashirot** [comment]
@guqing 如果是仅针对匿名用户，现有的返回值似乎无法提供邮箱hash
```json
{
  "metadata": {
    "finalizers": ["comment-protection"],
    "name": "6fdbad4e-be51-4c86-963d-37c127130204",
    "annotations": {},
    "version": 4,
    "creationTimestamp": "2024-04-02T10:41:53.020925300Z"
  },
  "spec": {
    "raw": "test2",
    "content": "test2",
    "owner": {
      "kind": "Email",
      "name": "",
      "displayName": "test2",
      "annotations": {
        "website": ""
      }
    },
    "userAgent": "Mozilla/5.0",
    "ipAddress": "",
    "approvedTime": "2024-04-02T10:42:02.813Z",
    "creationTime": "2024-04-02T10:41:53.020925300Z",
    "priority": 0,
    "top": false,
    "allowNotification": true,
    "approved": true,
    "hidden": false,
    "subjectRef": {
      "group": "content.halo.run",
      "version": "v1alpha1",
      "kind": "Post",
      "name": "5152aea5-c2e8-4717-8bba-2263d46e19d5"
    }
  },
  "status": {
    "replyCount": 0,
    "visibleReplyCount": 0,
    "unreadReplyCount": 0,
    "hasNewReply": false
  },
  "owner": {
    "kind": "Email",
    "displayName": "test2"
  },
  "stats": {
    "upvote": 0
  }
}
```

![image](https://github.com/halo-dev/plugin-comment-widget/assets/52254895/ca96fd43-3d82-48b3-8be7-38a7b7725d35)

或许可以在这个方法里将email的hash加入annotation或替换name？

**Comment by mashirot** [comment]
> 我的建议是在插件这边调用评论的 api 代理一下然后填充头像信息，也就是评论插件提供一个获取评论的 api 但是逻辑是先从 halo 获取数据然后处理头像在返回

不是很理解 `逻辑是先从 halo 获取数据`，相关的bean都没有开放给插件注入，halo返回的都是处理后的数据，插件套一层之后应该怎样填充头像信息呢，难道是重新造一套轮子吗

**Comment by ruibaby** [comment]
@mashirot 他的意思应该是通过 http api，相当于在评论插件中做一个中间层，然后评论组件调用评论插件的处理好的 api。

**Comment by mashirot** [comment]
> @mashirot 他的意思应该是通过 http api，相当于在评论插件中做一个中间层，然后评论组件调用评论插件的处理好的 api。

那样好像没啥意义，halo返回的数据没有邮箱相关字段，中间层也没法变出来

**Comment by ruibaby** [comment]
> > @mashirot 他的意思应该是通过 http api，相当于在评论插件中做一个中间层，然后评论组件调用评论插件的处理好的 api。
> 
> 
> 
> 那样好像没啥意义，halo返回的数据没有邮箱相关字段，中间层也没法变出来

确实，现在邮箱是脱敏了的。

**Comment by ruibaby** [comment]
> 目前我想到的有两种方案：
> 
> 
> 
> 1. Halo core 中提供一个扩展点，允许插件对评论数据进行修改。这样评论插件就可以实现该扩展点来实现想要的功能。
> 
> 2. Halo core 中默认把评论的邮箱进行 Hash 并设置到 annotations 中

我更推荐设计一个拓展点。

**Comment by JohnNiang** [comment]
方案一应当是实现的最终形态，方案二可快速验证当前的思路。

所以我推荐先用方案二实现，待验证成功且稳定后，再利用方案一来彻底实现，包括邮箱的脱敏也可以用扩展点来实现。

**Comment by mashirot** [comment]
> 方案一应当是实现的最终形态，方案二可快速验证当前的思路。
> 
> 所以我推荐先用方案二实现，待验证成功且稳定后，再利用方案一来彻底实现，包括邮箱的脱敏也可以用扩展点来实现。

https://github.com/halo-dev/halo/issues/5641
